### PR TITLE
bump hyper and mime vers

### PR DESCRIPTION
**Pull request by kavorite**

### CODE REVIEW

**Comment by mikedilger** [comment]
I see that this requires also your changes to the mime-multipart crate.  I'll start there.

Don't expect a quick turnaround as I'm pretty busy tonight and tomorrow is my Monday which is always busy.

**Comment by kavorite** [comment]
Understood. I'll start work on tests. Thank you!

**Comment by mikedilger** [comment]
hyper 11 is really quite a different paradigm.  It leaves me thinking that the public interfaces of mime-multipart and formdata are not appropriate in the tokio-based world... not that they couldn't work (your forks show that), but that when used this way you lose the asynchronicity (e.g. read_formdata() will block and your asynchronous server will not progress until read_formdata() has completed).

Personally I'm leaning towards entirely new crates, perhaps called `mime-mulitpart-async` and `formdata-async`.   I think hyper should have done that too.. so that the synchronous code could continue to be developed.

**Comment by kavorite** [comment]
Have you thought about whether you're going to employ nightly features?

On Sep 11, 2017 5:25 PM, "Michael Dilger" <notifications@github.com> wrote:

hyper 11 is really quite a different paradigm. It leaves me thinking that
the public interfaces of mime-multipart and formdata are not appropriate in
the tokio-based world... not that they couldn't work (your forks show
that), but that when used this way you lose the asynchronicity (e.g.
read_formdata() will block and your asynchronous server will not progress
until read_formdata() has completed).

Personally I'm leaning towards entirely new crates, perhaps called
mime-mulitpart-async and formdata-async. I think hyper should have done
that too.. so that the synchronous code could continue to be developed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mikedilger/formdata/pull/37#issuecomment-328663261>,
or mute
the thread

**Comment by mikedilger** [comment]
I don't think nightly features would be needed

**Comment by mikedilger** [comment]
Closing to to archival status

**Pull request closed without merging**
