### PR TITLE
Add nested multipart/mixed support

### LINKED ISSUE #2: Add handling for multipart/mixed
This is where a single multipart section is itself a multipart section.  This happens when a file input field is filled with multiple uploaded files.

### PR DESCRIPTION
**Pull request by SkylerLipthay**
I hope you don't mind that I did some proof-reading and conformed the codebase to a style more consistent with the official, evolving Rust style guide.

I also tried my hand at improving the public interface by reworking the "tuple of vectors of tuples" situation.

Most importantly, this PR should address and close #2. I ended up taking your advice and did not attempt deep `multipart/mixed` recursion. `multipart/mixed` sections only support file lists.

There's a fair amount of code duplication in the main tests that should be cleaned up. The state machine is now even beefier and could use some splitting up.

### CODE REVIEW

**Comment by SkylerLipthay** [comment]
Rebased to 0.3.1 master

**Comment by mikedilger** [comment]
I apologise, this PR slipped through the cracks somehow, I didn't notice until just now (and I'm not at the computer).  Thanks for your hard work, I'll look at it in the morning.

**Comment by mikedilger** [comment]
eh, I couldn't sleep.

This is just brilliant work Skyler.  Thanks.  I've merged it over my latest changes.

**Comment by SkylerLipthay** [comment]
Thanks for the merge! I'm successfully using this crate over at [`iron/params`](https://github.com/iron/params). The web app story is slowly coming together for Rust. :smile:

Thanks again for your valuable work.

**Comment by mikedilger** [comment]
If I had the time to upgrade my webtech to Iron I would definitely consider iron/params.  I've tried changing over to iron several times and fell into fits of mis-comprehension.  I'll try iron again at some point.

**Pull request merged**
